In [7]:
import pandas as pd

In [36]:
df = pd.read_csv('cleaned_data.csv')

In [37]:
df.head(10)

,review_id,company,product,review_text,sentiment_label
0,Cyndy,Amazon,Electronics,Disappointed Very disappointed that in order t...,somewhat negative
1,Musiciconic,Amazon,Electronics,Alright product for reading online books. Ther...,neutral
2,Chomie19,Amazon,Electronics,Great Tablet We had purchased this for our dau...,very positive
3,RCZon,Amazon,Electronics,A great tool to use to read and surf the inter...,very negative
4,scratcher36,Amazon,Electronics,GREAT REPLACEMENT NEW LARGER SCREENIS GREAT FO...,very positive
5,nikki3284,Amazon,Electronics,Great starter tablet I bought this for my kids...,somewhat positive
6,Cricket,Amazon,Electronics,Great for reading books on I purchased this to...,somewhat positive
7,Kevin,Amazon,Electronics,Works great I Ive used this for a month now. I...,neutral
8,3137299399,Amazon,Electronics,Kind of slow I like the price point for this t...,neutral
9,TJinFlorida,Amazon,Electronics,Hopefully more experience will helpl I'm not s...,somewhat positive

In [38]:
# randomly change half of "company" column to "BestBuy"
# randomly change half of "product" column to "Appliances"
import random
indices1 = list(range(len(df)))
indices2 = list(range(len(df)))
random.shuffle(indices1)
random.shuffle(indices2)
half = len(df) // 2
for i in indices1[:half]:
    df.at[i, 'company'] = 'BestBuy'
for i in indices2[:half]:
    df.at[i, 'product'] = 'Appliances'

In [39]:
df.head(10)

,review_id,company,product,review_text,sentiment_label
0,Cyndy,Amazon,Electronics,Disappointed Very disappointed that in order t...,somewhat negative
1,Musiciconic,BestBuy,Electronics,Alright product for reading online books. Ther...,neutral
2,Chomie19,Amazon,Appliances,Great Tablet We had purchased this for our dau...,very positive
3,RCZon,Amazon,Appliances,A great tool to use to read and surf the inter...,very negative
4,scratcher36,BestBuy,Appliances,GREAT REPLACEMENT NEW LARGER SCREENIS GREAT FO...,very positive
5,nikki3284,Amazon,Appliances,Great starter tablet I bought this for my kids...,somewhat positive
6,Cricket,Amazon,Appliances,Great for reading books on I purchased this to...,somewhat positive
7,Kevin,Amazon,Appliances,Works great I Ive used this for a month now. I...,neutral
8,3137299399,BestBuy,Electronics,Kind of slow I like the price point for this t...,neutral
9,TJinFlorida,Amazon,Electronics,Hopefully more experience will helpl I'm not s...,somewhat positive

In [42]:
df.to_csv('augmented_cleaned_data.csv', index=False, quoting=1)